version: "3.5"

services:
  db:
    image: mongo:latest
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rinha
      MONGO_INITDB_ROOT_PASSWORD: go-rocks
    ports:
      - "5432:5432"
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1GB"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 5s
      timeout: 5s
      start_period: 40s

  api1:
    image: devlucca/rinha
    restart: always
    hostname: api1
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"

  api2:
    image: devlucca/rinha
    restart: always
    hostname: api2
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"

  nginx:
    image: nginx:1.25.1-alpine
    hostname: api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"

  cache:
    hostname: cache
    image: redis:7-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.5GB"
    command: ["redis-server", "--save", "\"\"", "--appendonly", "no"]

networks:
  default:
    driver: bridge
