version: "3.5"

services:
  db:
    image: mysql:latest
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rinha
      MYSQL_ROOT_PASSWORD: gorocks
      MYSQL_DATABASE: rinha
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1GB"
    command: --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      start_period: 20s

  api1:
    image: devlucca/rinha
    restart: always
    hostname: api1
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: rinha
      DB_USER: root
      DB_PASS: gorocks

      CACHE_SERVER: cache
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"

  api2:
    image: devlucca/rinha
    restart: always
    hostname: api2
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: rinha
      DB_USER: root
      DB_PASS: gorocks

      CACHE_SERVER: cache
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"

  nginx:
    image: nginx:1.25.1-alpine
    hostname: api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"

  cache:
    hostname: cache
    image: redis:7-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.5GB"
    command: ["redis-server", "--save", "\"\"", "--appendonly", "no"]

networks:
  default:
    driver: bridge
